spring.application.name=user-api-server
spring.datasource.url=jdbc:mariadb://localhost:3306/proyecto-galleta
spring.datasource.username=root
spring.datasource.password=root2
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
jwt.secret=4Z8fQ2kN9pL3mR7sT1vX6bC0dE5gH8jK2nP4qS7uW9yA3cF6hJ0lM5oR8tV1xZ4
jwt.expiration=360000